import 'LocalParaVisitar.dart';
import 'hotel.dart';
class Cidade {
  final String nome;
  final List<Hotel> hoteis;
  final List<Localparavisitar> locais; 
  final String pathToImgHistoria;
  final String historia;

  Cidade({required this.nome, required this.hoteis, required this.locais, required this.pathToImgHistoria, required this.historia});
}



final List<Cidade> cidades = [
  Cidade(nome: 'São Sebastião', hoteis: hoteisSaoSebastiao, locais: locaisSaoSebastiao, pathToImgHistoria:'img/histsaosebastiao.png', historia: 'São Sebastião foi um dos primeiros povoados estabelecidos na costa brasileira, elevado à vila em 1636. Uma visita ao centro histórico nos leva a uma viagem de volta ao tempo. A cidade recebeu este nome em homenagem ao santo do dia em que passou a expedição de Américo Vespúcio em 1502. Seu povoamento se formou por consequência da ocupação de terras por sesmeiros portugueses vindos da Vila de Santos. Antes da colonização portuguesa, a região era ocupada por índios Tupinambás ao norte e Tupiniquins ao sul, sendo a Serra de Boiçucanga uma divisa natural das terras. Os escravos africanos também tiveram papel relevante no desenvolvimento de São Sebastião, já que em 1798 a cidade já contava com mais de 2300 escravos. O Centro Histórico de São Sebastião possui sete quarteirões e oito edifícios tombados isoladamente pelo Condephaat (Conselho de Defesa do Patrimônio Histórico, Artístico, Arquitetônico e Turístico do Estado).'),
  Cidade(nome: 'Guarujá', hoteis: hoteisGuaruja, locais: locaisGuaruja,pathToImgHistoria:'img/histguaruja.png', historia: 'A cidade de Guarujá, situada na Ilha de Santo Amaro, foi visitada pela primeira vez no dia 22 de Janeiro de 1502 pelos exploradores portugueses André Gonçalves, Américo Vespúcio e suas armadas. Mais precisamente, essa visita ocorreu na parte ocidental da ilha, conhecida atualmente como Praia Santa Cruz dos Navegantes. Contudo, devido à topografia, hostilidade indígena e áreas pantanosas a cidade ficou por mais de 300 anos abandonada. Tendo apenas a extração de óleo de baleia, pesca e poucos engenhos de açúcar como atividade econômica. Com o passar do tempo as pessoas que viviam dessa economia foram formando um pequeno povoado, sendo assim, por um decreto imperial de 1832, Guarujá passou a condição de Vila. Em 1893, Guarujá foi promovida a Vila Balneária de Guarujá. Para isso foram encomendados dos Estados Unidos um hotel, uma igreja, um cassino e 46 chalés residenciais desmontáveis. Além de receber serviços de água, esgoto e luz elétrica. Em 30 de Junho de 1934 a cidade recebeu o título de Estância Balneária e em 1947 passou a ser considerada município devido ao seu crescimento contínuo. Com uma natureza exuberante espalhada por 27 praias com belezas totalmente diferentes que atraiam os turistas para a região, Guarujá foi reconhecido internacionalmente, na década de 70, com o título de “Pérola do Atlântico”. Atualmente a cidade continua a ser referência nacional na qualidade de suas praias, o desenvolvimento econômico das últimas décadas trouxe grandes investimentos ao setor portuário, náutico, hoteleiro, empresarial, imobiliário e do comércio. Hoje Guarujá é o destino ideal para quem quer desfrutar das belezas naturais e garantir e um passeio com muita diversão e cultura.'),
  Cidade(nome: 'Santos', hoteis: hoteisSantos, locais: locaisSantos, pathToImgHistoria:'img/histsantos.png', historia: 'Fundada em 1546 por Brás Cubas, sendo uma das cidades mais antigas das Américas, Santos tornou um centro do ciclo do café no século XIX. Em 1922, foi inaugurada a Bolsa Oficial do Café, onde eram negociadas riquezas do mercado cafeeiro para o país e que resultou no atual Museu do Café no Centro Histórico, que promove exposições sobre a trajetória do produto pelo Brasil e pela cidade e que é decorado com obras do artista Benedito Calixto. Atualmente, Santos possui uma pujante, principalmente por conta de seu complexo portuário. Em 2016, a cidade era a 33ª mais rica do país, com produto interno bruto de 21 954 556,74 de reais.'),
  Cidade(nome: 'Ubatuba', hoteis: hoteisUbatuba, locais: locaisUbatuba, pathToImgHistoria:'img/histubatuba.png', historia: 'No século XVI, Ubatuba fazia parte de uma região litorânea maioritariamente ocupada pelos indígenas tupinambás. A primeira possível referência ao local aparece na obra de Hans Staden, que permaneceu cativo numa aldeia chamada Uwatibi, em Angra dos Reis. Essa aldeia tinha o mesmo nome do local da atual cidade de Ubatuba, sítio em que os índios tupinambás se reuniam com muitas canoas para expedições de guerra contra os tupiniquins e os portugueses em Burikioca (Bertioga) e Upau-Nema (São Vicente). Tanto Hans Staden quanto outros autores europeus da época mencionam que o chefe supremo dos tupinambás era Cunhambebe e que seu território se estendia desde o Rio Juqueriquerê, em Caraguatatuba, até o Cabo de São Tomé, no leste do estado do Rio de Janeiro, abrangendo também todo o território ao longo do Rio Paraíba do Sul. Apenas décadas mais tarde, nos relatos de José de Anchieta, é que encontramos menção à aldeia de Iperoig, que pode significar "rio do tubarão" ou "rio das perobas". Os índios tupinambás estiveram entre os primeiros índios brasileiros a sofrer o impacto dos portugueses, uma vez que foram escravizados para os engenhos de cana-de-açúcar em São Vicente. Isso motivou uma firme aliança dos tupinambás com os franceses da França Antártica, que ocuparam a região da baía de Guanabara. Essa aliança, liderada por Cunhambebe, ficou conhecida como Confederação dos Tamoios. Em 1563, José de Anchieta partiu com Manuel da Nóbrega de São Vicente para a aldeia de Iperoig, com o objetivo de pacificar os tupinambás. Anchieta permaneceu refém durante vários meses em Iperoig, enquanto Manuel da Nóbrega voltou a São Vicente acompanhado de Cunhambebe para acertar o tratado de paz conhecido como Paz de Iperoig. Com a paz estabelecida com os índios tupinambás fronteiriços a São Vicente, os portugueses destruíram boa parte da nação tupinambá em conflitos na baía de Guanabara (em Uruçumirim - atual aterro do Flamengo) e em Cabo Frio, expulsando os franceses da região.'),
];
